name: Run Tests and Coverage

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-and-cover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Run tests with nuke
        run: ./build/build.sh -Target Test -Configuration Debug
